services:
  - type: web
    name: sarazapatos
    runtime: php
    plan: free
    buildCommand: "./build.sh"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    envVars:
      - key: APP_KEY
        generate: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false